---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./jetstack.yaml
  - ./prometheus-community.yaml
  - ./ingress-nginx.yaml
  - ./cilium.yaml
  - ./openebs.yaml
  - ./coredns.yaml
  - ./cloudnative-pg.yaml
